const data = {
  products: [
    {
      name: "BLACK DRESS",
      slug: "BLACK DRESS",
      category: "DRESS",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality dress",
    },
    {
      name: "HIGH HEELS",
      slug: "HIGH HEELS",
      category: "HEELS",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "NUDE DRESS",
      slug: "NUDE DRESS",
      category: "DRESS",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "GUCCI HANDBAG",
      slug: "HANDBAG",
      category: "HANDBAG",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Gucci",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
